package SunumKatmani;


import javax.swing.JOptionPane;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sametozeren
 */
public class AnaMenu extends javax.swing.JFrame {

    /**
     * Creates new form AnaMenu
     */
    public AnaMenu() {
        super("Kütüphanem Ana Menü");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblBaslik = new javax.swing.JLabel();
        lblHos = new javax.swing.JLabel();
        islemlerpnl = new javax.swing.JPanel();
        lblYeniKitap = new javax.swing.JLabel();
        btnYeniKitap = new javax.swing.JButton();
        btnYeniOgrenci = new javax.swing.JButton();
        lblYeniOgrenci = new javax.swing.JLabel();
        btnKitapVer = new javax.swing.JButton();
        lblKitapVer = new javax.swing.JLabel();
        btnKitapAl = new javax.swing.JButton();
        lblKitapAl = new javax.swing.JLabel();
        anamenubar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBaslik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBaslik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/bookshelf (1).png"))); // NOI18N
        lblBaslik.setText("Kütüphanem");

        lblHos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHos.setText("Hoşgeldiniz");

        lblYeniKitap.setText("Kitap İşlemleri");

        btnYeniKitap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/reading.png"))); // NOI18N
        btnYeniKitap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniKitapActionPerformed(evt);
            }
        });

        btnYeniOgrenci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/man.png"))); // NOI18N
        btnYeniOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniOgrenciActionPerformed(evt);
            }
        });

        lblYeniOgrenci.setText("Öğrenci İşlemleri");

        btnKitapVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/notebook (1).png"))); // NOI18N
        btnKitapVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapVerActionPerformed(evt);
            }
        });

        lblKitapVer.setText("Kitap Al");

        btnKitapAl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/notebook.png"))); // NOI18N
        btnKitapAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapAlActionPerformed(evt);
            }
        });

        lblKitapAl.setText("Teslim Et");

        javax.swing.GroupLayout islemlerpnlLayout = new javax.swing.GroupLayout(islemlerpnl);
        islemlerpnl.setLayout(islemlerpnlLayout);
        islemlerpnlLayout.setHorizontalGroup(
            islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(islemlerpnlLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnYeniKitap)
                    .addComponent(lblYeniKitap)
                    .addComponent(btnKitapVer)
                    .addComponent(lblKitapVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lblKitapAl)
                        .addComponent(btnKitapAl)
                        .addComponent(lblYeniOgrenci))
                    .addComponent(btnYeniOgrenci))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        islemlerpnlLayout.setVerticalGroup(
            islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(islemlerpnlLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnYeniKitap)
                    .addComponent(btnYeniOgrenci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, islemlerpnlLayout.createSequentialGroup()
                        .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYeniKitap)
                            .addComponent(lblYeniOgrenci))
                        .addGap(18, 18, 18)
                        .addComponent(btnKitapVer))
                    .addComponent(btnKitapAl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKitapVer)
                    .addComponent(lblKitapAl))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("Dosya");

        menuCikis.setText("Çıkış");
        menuCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCikisActionPerformed(evt);
            }
        });
        jMenu1.add(menuCikis);

        anamenubar.add(jMenu1);

        setJMenuBar(anamenubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBaslik)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHos)
                                .addContainerGap())))
                    .addComponent(islemlerpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblBaslik))
                            .addComponent(lblLogo)))
                    .addComponent(lblHos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(islemlerpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(480, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCikisActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Giris yeni = new Giris();
        yeni.setVisible(true);
    }//GEN-LAST:event_menuCikisActionPerformed

    private void btnYeniKitapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniKitapActionPerformed
        // TODO add your handling code here:
        if (Giris.durum==0) {
            JOptionPane.showMessageDialog(null, "Öğrenci Olduğunuz için bu işlemi yapamazsınız");
        }
        else{
            setVisible(false);
            Kitaplar yeni = new Kitaplar();
            yeni.setVisible(true);
        }
        
    }//GEN-LAST:event_btnYeniKitapActionPerformed

    private void btnYeniOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniOgrenciActionPerformed
        // TODO add your handling code here:
        if (Giris.durum==0) {
            JOptionPane.showMessageDialog(null, "Öğrenci Olduğunuz için bu işlemi yapamazsınız");
        }
        else{
        setVisible(false);
        Ogrenciler yeni = new Ogrenciler();
        yeni.setVisible(true);
        }
    }//GEN-LAST:event_btnYeniOgrenciActionPerformed

    private void btnKitapVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapVerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        KitapVer yeni = new KitapVer();
        yeni.setVisible(true);
    }//GEN-LAST:event_btnKitapVerActionPerformed

    private void btnKitapAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapAlActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        KitapAl yeni = new KitapAl();
        yeni.setVisible(true);
    }//GEN-LAST:event_btnKitapAlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar anamenubar;
    private javax.swing.JButton btnKitapAl;
    private javax.swing.JButton btnKitapVer;
    public javax.swing.JButton btnYeniKitap;
    private javax.swing.JButton btnYeniOgrenci;
    private javax.swing.JPanel islemlerpnl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lblBaslik;
    private javax.swing.JLabel lblHos;
    private javax.swing.JLabel lblKitapAl;
    private javax.swing.JLabel lblKitapVer;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblYeniKitap;
    private javax.swing.JLabel lblYeniOgrenci;
    private javax.swing.JMenuItem menuCikis;
    // End of variables declaration//GEN-END:variables
}
