package SunumKatmani;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import İsKatmani.KitapHareketleri;
import İsKatmani.Kitap;
import İsKatmani.Uye;
import İsKatmani.VeriTransferFonksiyonlari.KitapAlisVerisFunc;
import İsKatmani.VeriTransferFonksiyonlari.KitaplarFunc;
import İsKatmani.VeriTransferFonksiyonlari.OgrencilerFunc;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sametozeren
 */
public class KitapVer extends javax.swing.JFrame {
    /**
     * Creates new form KitapVer
     */
    OgrencilerFunc ogr = new OgrencilerFunc();
    KitaplarFunc kitap = new KitaplarFunc();
    public KitapVer() {
        super("Emanet Kitap Ver");
        initComponents();
        ogrenciTable.setModel(DbUtils.resultSetToTableModel(ogr.listele()));
        kitapTable.setModel(DbUtils.resultSetToTableModel(kitap.stokListele()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kitapVerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        btngeri = new javax.swing.JButton();
        dateverilistarihi = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        ogrenciTable = new javax.swing.JTable();
        btnOgrSec = new javax.swing.JButton();
        btnKitapSeç = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kitapTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Veriliş Tarihi");

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/agenda.png"))); // NOI18N
        btnVer.setText("Kitap Al");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btngeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/back.png"))); // NOI18N
        btngeri.setText("Geri");
        btngeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeriActionPerformed(evt);
            }
        });

        ogrenciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ogrenciTable);

        btnOgrSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/reading (1).png"))); // NOI18N
        btnOgrSec.setText("Öğrenci Seç");
        btnOgrSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrSecActionPerformed(evt);
            }
        });

        btnKitapSeç.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/books.png"))); // NOI18N
        btnKitapSeç.setText("Kitap Seç");
        btnKitapSeç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapSeçActionPerformed(evt);
            }
        });

        kitapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(kitapTable);

        jLabel2.setText("Öğrenciler");

        jLabel3.setText("Kitaplar");

        jLabel4.setText("NOT: Sol taraftan öğrenci seçtikten sonra öğrenci");

        jLabel5.setText("seç butonuna basınız ve sonrasında sağ taraftan");

        jLabel6.setText("kitap seçimi yapınız ardından kitap seç butonuna ");

        jLabel7.setText("tıklayınız.Bu işlemlerden sonra tarih seçerek");

        jLabel8.setText("kitap ver butonuna tıklayınız");

        javax.swing.GroupLayout kitapVerPanelLayout = new javax.swing.GroupLayout(kitapVerPanel);
        kitapVerPanel.setLayout(kitapVerPanelLayout);
        kitapVerPanelLayout.setHorizontalGroup(
            kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateverilistarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                        .addComponent(btnVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btngeri))
                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                        .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitapVerPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                                        .addGap(392, 392, 392)
                                        .addComponent(btnOgrSec, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnKitapSeç, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)))
                        .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kitapVerPanelLayout.setVerticalGroup(
            kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOgrSec)
                    .addComponent(btnKitapSeç))
                .addGap(55, 55, 55)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateverilistarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVer)
                    .addComponent(btngeri))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Emanet Kitap Al");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(kitapVerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kitapVerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1146, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btngeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeriActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AnaMenu yeni = new AnaMenu();
        yeni.setVisible(true);
    }//GEN-LAST:event_btngeriActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        KitapHareketleri hazirla = new KitapHareketleri();
        hazirla.Kit_Id = secilenkit;
        hazirla.Uye_Id = secilenogr;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String tarih = dateFormat.format(dateverilistarihi.getDate());
        hazirla.VerilisTarihi = tarih;
        KitapAlisVerisFunc gonder = new KitapAlisVerisFunc();
        gonder.ekle(hazirla);
    }//GEN-LAST:event_btnVerActionPerformed
    int secilenogr;
    private void btnOgrSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrSecActionPerformed
        // TODO add your handling code here:
        int tablosatir= ogrenciTable.getSelectedRow();//Hangi satır olduğunu alıyor.
        secilenogr=(int) ogrenciTable.getValueAt(tablosatir,0);
        OgrencilerFunc getir = new OgrencilerFunc();
        Uye gelen = getir.ogrenciGetir(secilenogr);
        JOptionPane.showMessageDialog(null, "Seçilen Öğrenci: "+gelen.isim);
    }//GEN-LAST:event_btnOgrSecActionPerformed
    int secilenkit;
    private void btnKitapSeçActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapSeçActionPerformed
        // TODO add your handling code here:
        int tablosatir= kitapTable.getSelectedRow();//Hangi satır olduğunu alıyor.
        secilenkit=(int) kitapTable.getValueAt(tablosatir,0);
        KitaplarFunc getir = new KitaplarFunc();
        Kitap gelen = getir.kitapGetir(secilenkit);
        JOptionPane.showMessageDialog(null, "Seçilen Kitap: "+gelen.isim);
    }//GEN-LAST:event_btnKitapSeçActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapVer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKitapSeç;
    private javax.swing.JButton btnOgrSec;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btngeri;
    private com.toedter.calendar.JDateChooser dateverilistarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable kitapTable;
    private javax.swing.JPanel kitapVerPanel;
    private javax.swing.JTable ogrenciTable;
    // End of variables declaration//GEN-END:variables
}
