package SunumKatmani;






import VeriKatmani.javaBaglanti;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import İsKatmani.KitapHareketleri;
import İsKatmani.Kitap;
import İsKatmani.Uye;
import İsKatmani.VeriTransferFonksiyonlari.KitapAlisVerisFunc;
import İsKatmani.VeriTransferFonksiyonlari.KitaplarFunc;
import İsKatmani.VeriTransferFonksiyonlari.OgrencilerFunc;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sametozeren
 */
public class KitapAl extends javax.swing.JFrame {
    /**
     * Creates new form KitapAl
     */
    OgrencilerFunc ogr = new OgrencilerFunc();
    KitaplarFunc kitap = new KitaplarFunc();
    public KitapAl() {
        super("Emanet Kitap Teslim Al");
        initComponents();
        ogrenciTable.setModel(DbUtils.resultSetToTableModel(ogr.listele()));
        kitapTable.setModel(DbUtils.resultSetToTableModel(kitap.stokDisiListele()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kitapAlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAl = new javax.swing.JButton();
        btngeri = new javax.swing.JButton();
        dateteslimtarihi = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        ogrenciTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kitapTable = new javax.swing.JTable();
        btnKitapSeç = new javax.swing.JButton();
        btnOgrSec = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Teslim Tarihi");

        btnAl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/agenda.png"))); // NOI18N
        btnAl.setText("Teslim Et");
        btnAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlActionPerformed(evt);
            }
        });

        btngeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/back.png"))); // NOI18N
        btngeri.setText("Geri");
        btngeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeriActionPerformed(evt);
            }
        });

        ogrenciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ogrenciTable);

        jLabel2.setText("Öğrenciler");

        jLabel3.setText("Kitaplar");

        kitapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(kitapTable);

        btnKitapSeç.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/books.png"))); // NOI18N
        btnKitapSeç.setText("Kitap Seç");
        btnKitapSeç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapSeçActionPerformed(evt);
            }
        });

        btnOgrSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/reading (1).png"))); // NOI18N
        btnOgrSec.setText("Öğrenci Seç");
        btnOgrSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrSecActionPerformed(evt);
            }
        });

        jLabel4.setText("NOT: Sol taraftan öğrenci seçtikten sonra öğrenci");

        jLabel5.setText(" seç butonuna basınız ve sonrasında sağ taraftan");

        jLabel6.setText("kitap seçimi yapınız ardından kitap seç butonuna ");

        jLabel7.setText("tıklayınız.Bu işlemlerden sonra tarih seçerek ");

        jLabel8.setText("kitap ver butonuna tıklayınız");

        javax.swing.GroupLayout kitapAlPanelLayout = new javax.swing.GroupLayout(kitapAlPanel);
        kitapAlPanel.setLayout(kitapAlPanelLayout);
        kitapAlPanelLayout.setHorizontalGroup(
            kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitapAlPanelLayout.createSequentialGroup()
                .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kitapAlPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btngeri))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitapAlPanelLayout.createSequentialGroup()
                        .addGap(0, 424, Short.MAX_VALUE)
                        .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitapAlPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateteslimtarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitapAlPanelLayout.createSequentialGroup()
                                .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kitapAlPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitapAlPanelLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOgrSec, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnKitapSeç, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(kitapAlPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3)
                    .addGap(354, 354, 354)))
        );
        kitapAlPanelLayout.setVerticalGroup(
            kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitapAlPanelLayout.createSequentialGroup()
                .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kitapAlPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kitapAlPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(26, 26, 26)
                .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateteslimtarihi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAl)
                    .addComponent(btngeri))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kitapAlPanelLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOgrSec)
                            .addComponent(btnKitapSeç)))
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Emanet Kitap Teslim Et");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kitapAlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kitapAlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlActionPerformed
        // TODO add your handling code here:
        KitapHareketleri hazirla = new KitapHareketleri();
        hazirla.Kit_Id = secilenkit;
        hazirla.Uye_Id = secilenogr;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String tarih = dateFormat.format(dateteslimtarihi.getDate());
        hazirla.TeslimTarihi = tarih;
        KitapAlisVerisFunc gonder = new KitapAlisVerisFunc();
        gonder.guncelle(hazirla);
    }//GEN-LAST:event_btnAlActionPerformed

    private void btngeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeriActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AnaMenu yeni = new AnaMenu();
        yeni.setVisible(true);
    }//GEN-LAST:event_btngeriActionPerformed
    int secilenkit;
    private void btnKitapSeçActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapSeçActionPerformed
        // TODO add your handling code here:
        int tablosatir= kitapTable.getSelectedRow();//Hangi satır olduğunu alıyor.
        secilenkit=(int) kitapTable.getValueAt(tablosatir,0);
        KitaplarFunc getir = new KitaplarFunc();
        Kitap gelen = getir.kitapGetir(secilenkit);
        JOptionPane.showMessageDialog(null, "Seçilen Kitap: "+gelen.isim);
    }//GEN-LAST:event_btnKitapSeçActionPerformed
    int secilenogr;
    private void btnOgrSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrSecActionPerformed
        // TODO add your handling code here:
        int tablosatir= ogrenciTable.getSelectedRow();//Hangi satır olduğunu alıyor.
        secilenogr=(int) ogrenciTable.getValueAt(tablosatir,0);
        OgrencilerFunc getir = new OgrencilerFunc();
        Uye gelen = getir.ogrenciGetir(secilenogr);
        JOptionPane.showMessageDialog(null, "Seçilen Öğrenci: "+gelen.isim);
    }//GEN-LAST:event_btnOgrSecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapAl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAl;
    private javax.swing.JButton btnKitapSeç;
    private javax.swing.JButton btnOgrSec;
    private javax.swing.JButton btngeri;
    private com.toedter.calendar.JDateChooser dateteslimtarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel kitapAlPanel;
    private javax.swing.JTable kitapTable;
    private javax.swing.JTable ogrenciTable;
    // End of variables declaration//GEN-END:variables
}
