package SunumKatmani;

import javax.swing.JOptionPane;
import İsKatmani.Uye;
import İsKatmani.VeriTransferFonksiyonlari.OgrencilerFunc;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sametozeren
 */
public class YeniOgrenci extends javax.swing.JFrame {
    /**
     * Creates new form YeniOgrenci
     */
    
    public YeniOgrenci() {
        super("Yeni Öğrenci Ekle");
        initComponents();
    }

    /**Connection baglan;
    ResultSet rs;
    PreparedStatement pst;
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yeniogrencieklepnl = new javax.swing.JPanel();
        lblbol = new javax.swing.JLabel();
        lblalan = new javax.swing.JLabel();
        lbldonem = new javax.swing.JLabel();
        txtisim = new javax.swing.JTextField();
        txtalan = new javax.swing.JTextField();
        cmbsinif = new javax.swing.JComboBox<>();
        lblisim = new javax.swing.JLabel();
        cmbyil = new javax.swing.JComboBox<>();
        btnKayit = new javax.swing.JButton();
        lblyil = new javax.swing.JLabel();
        cmbdonem = new javax.swing.JComboBox<>();
        btnGeri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yeniogrencieklepnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)), "Yeni Öğrenci Ekle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        lblbol.setText("Bölüm");

        lblalan.setText("Alan");

        lbldonem.setText("Dönem");

        cmbsinif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bilgisayar Mühendisliği", "Eltrik-Elektronik Mühendisliği", "İnşaat Mühendisliği" }));

        lblisim.setText("İsim");

        cmbyil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));

        btnKayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/add.png"))); // NOI18N
        btnKayit.setText("Ekle");
        btnKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitActionPerformed(evt);
            }
        });

        lblyil.setText("Yıl");

        cmbdonem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        btnGeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunumKatmani/image/back.png"))); // NOI18N
        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yeniogrencieklepnlLayout = new javax.swing.GroupLayout(yeniogrencieklepnl);
        yeniogrencieklepnl.setLayout(yeniogrencieklepnlLayout);
        yeniogrencieklepnlLayout.setHorizontalGroup(
            yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniogrencieklepnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yeniogrencieklepnlLayout.createSequentialGroup()
                        .addGroup(yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblisim)
                            .addComponent(lblbol)
                            .addComponent(lblyil)
                            .addComponent(lbldonem)
                            .addComponent(lblalan))
                        .addGap(36, 36, 36)
                        .addGroup(yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtisim)
                            .addComponent(cmbsinif, 0, 265, Short.MAX_VALUE)
                            .addComponent(txtalan)
                            .addComponent(cmbyil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbdonem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yeniogrencieklepnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKayit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeri, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        yeniogrencieklepnlLayout.setVerticalGroup(
            yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniogrencieklepnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblisim)
                    .addComponent(txtisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbol)
                    .addComponent(cmbsinif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblalan)
                    .addComponent(txtalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblyil)
                    .addComponent(cmbyil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldonem)
                    .addComponent(cmbdonem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniogrencieklepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGeri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKayit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yeniogrencieklepnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(yeniogrencieklepnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Ogrenciler yeni = new Ogrenciler();
        yeni.setVisible(true);
    }//GEN-LAST:event_btnGeriActionPerformed

    private void btnKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitActionPerformed
        // TODO add your handling code here:
        Uye yeni = new Uye();
        yeni.isim = txtisim.getText();
        yeni.bolum = (String)cmbsinif.getSelectedItem();
        yeni.alan = txtalan.getText();
        yeni.yil = (String)cmbyil.getSelectedItem();
        yeni.donem = (String)cmbdonem.getSelectedItem();
        OgrencilerFunc ogrenci = new OgrencilerFunc();
        ogrenci.ekle(yeni);
    }//GEN-LAST:event_btnKayitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YeniOgrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YeniOgrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YeniOgrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YeniOgrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YeniOgrenci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnKayit;
    private javax.swing.JComboBox<String> cmbdonem;
    private javax.swing.JComboBox<String> cmbsinif;
    private javax.swing.JComboBox<String> cmbyil;
    private javax.swing.JLabel lblalan;
    private javax.swing.JLabel lblbol;
    private javax.swing.JLabel lbldonem;
    private javax.swing.JLabel lblisim;
    private javax.swing.JLabel lblyil;
    private javax.swing.JTextField txtalan;
    private javax.swing.JTextField txtisim;
    private javax.swing.JPanel yeniogrencieklepnl;
    // End of variables declaration//GEN-END:variables
}
